# Generated by Django 4.0.6 on 2023-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='содержание профиля проверено'),
        ),
    ]
