FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install libpq-dev python3-dev -y

COPY apis/requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY core /app/core
COPY rabbit /app/rabbit
COPY db /app/db
COPY /media /media
COPY models /app/models
COPY apis /app/apis

WORKDIR /app/apis

EXPOSE 8001