FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install libpq-dev python3-dev -y
RUN  pip install --upgrade pip


COPY admin_panel/requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY core /app/core
COPY db /app/db
COPY /media /media
COPY admin_panel /app/admin_panel

WORKDIR /app/admin_panel/app

# RUN python manage.py makemigrations --noinput
# RUN python manage.py migrate --noinput

# Create superuser during image build
# RUN python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); \
# User.objects.filter(email='admin@gmail.com').exists() or \
# User.objects.create_superuser('admin', 'admin@gmail.com', 'admin')"

EXPOSE 8000