version: '3.9'

services:
#  app:
#    build:
#      context: .
#    command: >
#      sh -c "python manage.py migrate &&
#             python manage.py runserver 0.0.0.0:8000"
#    ports:
#      - 8000:8000
#    volumes:
#      - ./app:/app
#      - ./data/web:/vol/web
#    environment:
#      - SECRET_KEY=devsecretkey
#      - DEBUG=1
#      - DB_HOST=db
#      - DB_NAME=config
#      - DB_USER=postgresql
#      - DB_PASS=postgresql
#    depends_on:
#      - db
  bot_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1097:1097"
#
#  rabbit:
#    build:
#      context: rabbit
#      dockerfile: Dockerfile
#    ports:
#      - "5672:5672"
#
#  db:
#    image: postgres:13-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=config
#      - POSTGRES_USER=postgresql
#      - POSTGRES_PASSWORD=postgresql

#  bot:
#    build:
#      context: .
#    command: >
#      sh -c "python3 ./aiogramBot/main.py"
#    ports:
#      - 6432:6432
#    volumes:
#      - ./aiogramBot:/aiogramBot
#    environment:
#     - DATABASE_URL=postgresql://postgresql:postgresql@0.0.0.0:5432/config
#    depends_on:
#      - db