FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install libpq-dev python3-dev -y
RUN  pip install --upgrade pip
RUN  pip install umap-learn bechdelai==0.0.1a2


COPY admin_panel/requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY core /app/core
COPY db /app/db
COPY /media /media
COPY admin_panel /app/admin_panel

WORKDIR /app/admin_panel/app

EXPOSE 8000