FROM python:3.10

WORKDIR /app

RUN apt-get update && apt-get install libpq-dev python3-dev -y
RUN  pip install --upgrade pip

COPY psychologists_bot/requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

COPY core /app/core
COPY db /app/db
COPY models /app/models
COPY /media /media
COPY redis_ /app/redis_
COPY psychologists_bot /app/psychologists_bot

WORKDIR /app

CMD ["python3", "-u", "psychologists_bot/main.py"]