# Generated by Django 4.0.6 on 2022-07-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('description', models.TextField(max_length=1000, verbose_name='о психологе')),
                ('photo', models.ImageField(default='', upload_to='', verbose_name='путь к фото')),
                ('meet_price', models.IntegerField(default=0, verbose_name='стоимость сеанас Р')),
                ('likes', models.IntegerField(default=0, verbose_name='оценки нравится')),
            ],
            options={
                'verbose_name': 'Психолог',
                'verbose_name_plural': 'Психологи',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(max_length=20, verbose_name='День недели')),
                ('psychologist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.psychologist')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='название тарифа')),
                ('meets', models.IntegerField(verbose_name='количество встреч в неделю')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(default=None, null=True, verbose_name='Начало сеанса')),
                ('time_end', models.TimeField(default=None, null=True, verbose_name='Конец сеанса')),
                ('time_is_busy', models.BooleanField(verbose_name='Время забронировано')),
                ('meets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.schedule')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('tg_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id телеграмм аккаунта клиента')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('psycho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.psychologist')),
                ('tariff', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.tariff')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
