# Generated by Django 4.0.6 on 2022-07-19 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0003_alter_schedule_day_of_the_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.client'),
        ),
    ]
