# Generated by Django 4.0.6 on 2022-07-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0005_remove_client_psycho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(default=None, null=True, verbose_name='Начало сеанса')),
                ('time_end', models.TimeField(default=None, null=True, verbose_name='Конец сеанса')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='tariff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.tariff'),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AddField(
            model_name='meet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.client'),
        ),
        migrations.AddField(
            model_name='meet',
            name='day_of_the_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psychoapp.schedule'),
        ),
    ]
