# Generated by Django 4.0.6 on 2022-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0007_client_remaining_meets'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='tg_link',
            field=models.CharField(default='', max_length=30, verbose_name='ссылка на летеграм'),
        ),
    ]
