# Generated by Django 4.0.6 on 2022-07-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='meets',
            new_name='day_of_the_week',
        ),
    ]
