# Generated by Django 4.0.6 on 2022-07-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0002_rename_meets_time_day_of_the_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day_of_the_week',
            field=models.CharField(max_length=20, unique=True, verbose_name='День недели'),
        ),
    ]
