# Generated by Django 4.0.6 on 2022-07-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychoapp', '0006_meet_alter_client_tariff_delete_time_meet_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='remaining_meets',
            field=models.IntegerField(default=0, verbose_name='Сеансов осталось'),
        ),
    ]
